### ISSUE TITLE
Cgo / pkg-config dependency for Journal Reading

### ISSUE THREAD

**Issue by pquerna** [coreos/go-systemd#115]
Since https://github.com/coreos/go-systemd/pull/110 go-systemd now uses Cgo, and depends on both `libsystemd-journal` (at build and runtime) and `pkg-config` (at build).  These new dependencies are only used by the code for reading from the systemd journal.

This is moderately inconvenient, as previously go-systemd only used native Go packages to communicate with the journal or systemd.

Ideally native Go could be used, but maybe hiding the journal-reading feature behind a build flag hides the pain.

CC @philips @jonboulle

**Comment by jzelinskie** [comment]
+1 [capnslog](https://github.com/coreos/pkg/capnslog) uses this to detect if it's running under systemd and ships off directly to the journal, and I'd rather not have a logging library that requires cgo.
