### ISSUE TITLE
sdjournal: Enumerate the fields

### ISSUE THREAD

**Issue by tv42** [coreos/go-systemd#142]
Right now, `sdjournal` only lets you access fields you already know to expect. The C library has `sd_journal_enumerate_data` for accessing all fields of a single message, and `sd_journal_enumerate_fields` for listing all fields that all messages in the journal contain.

https://www.freedesktop.org/software/systemd/man/sd_journal_get_data.html
https://www.freedesktop.org/software/systemd/man/sd_journal_enumerate_fields.html

**Comment by jonboulle** [comment]
Seems perfectly reasonable, feel free to submit a patch!

**Comment by lucab** [comment]
@tv42 #164 is being reviewed at the moment, and if I've understood correctly is should address your request. Care to chime in there to check that it fits your usecase?

**Comment by tv42** [comment]
@lucab Seems like it would.
