### ISSUE TITLE
get compilation error when use sdjournal

### ISSUE THREAD

**Issue by AdoHe** [coreos/go-systemd#201]
FYI. When I test sdjournal, I got this error:
```
systemd/sd-journal.h: No such file or directory
compilation terminated
```
@jonboulle

**Comment by lucab** [comment]
Hi @AdoHe, I'm unfortunately missing a bit of context regarding your report.

How are you building this? Which OS and version? In order to build the `sdjournal` package you need to have the `libsystemd` development/headers files available in your system search path; are they installed?

**Comment by darkonie** [comment]
@AdoHe I am pretty sure you need `libsystemd` headers. If you are using ubuntu/debian you can just run `apt-get update && apt-get install libsystemd-dev`.

**Comment by AdoHe** [comment]
@lucab @darkonie yes, I am confirm this, thanks very much.

**Comment by lucab** [comment]
@AdoHe Thanks for following up. Not a bug, closing.

**Comment by heartbeat2015** [comment]
what's package for centos

**Comment by heartbeat2015** [comment]
yum install systemd-devel   can work on centos7
