### ISSUE TITLE
Investigate one-to-one dbus calling

### ISSUE THREAD

**Issue by lucab** [coreos/go-systemd#207]
go-systemd currently relies on an existing dbus system bus in order to invoke systemd methods. However, this may be not strictly needed as systemd itself exposes a UNIX socket for one-to-one dbus calling at `/var/run/systemd/private`.

It may be possible to implement a fallback mechanism, in order to retry connecting to the p2p endpoint if the system bus doesn't exist. However this needs a bit more investigation to determine if this works in a transparent way, and the same set of methods/properties are available.

**Comment by lucab** [comment]
Assigning to @squeed for the initial investigation. This may help removing a dbus requirement from some tools expected to run in minimal environments, like runc.

**Comment by squeed** [comment]
This is already supported, but needs to be explicitly requested. If we like, we could change the logic of `New()` to reflect systemd's logic: connect to the private bus if `uid == 0`.

**Comment by jonboulle** [comment]
What guarantee do we have that it's 1:1 with dbus? I'm wary because of https://github.com/systemd/systemd/issues/3610#issuecomment-229679807

**Comment by squeed** [comment]
We don't have that guarantee per se. However, all the current systemd tools operate this way - they try kdbus, then private socket, then public bus.
We have some important scenarios where we need to talk to systemd without dbus running, so adding this as a fallback would be really useful.

**Comment by lucab** [comment]
No explicit guarantee, but systemd internally is doing this [kind of automatic fallback](https://github.com/systemd/systemd/blob/v231/src/shared/bus-util.c#L585) so it seems to handle all cases transparently without special-casing endpoints on different buses. I think this gave us some confidence margin that there won't be big differences.

Just to be more conservative, second iteration of #208 switched to using the p2p mode only as a fallback if the original dbus connection fails. Sounds more reasonable?
