### ISSUE TITLE
Additional Machined functionality

### ISSUE THREAD

**Issue by cpg1111** [coreos/go-systemd#213]
Hi there,

I was taking a looking at go-systemd's machined functionality and I was wondering how come there's only `RegisterMachine()`?  

If adding additional functionality in there is something desired, I'd be happy to submit a pull request adding features such as GetMachine, GetImage, ListMachines, TerminateMachine, etc.  And if it'd be preferred that I add each one in a separate Pull Request, I can do that as well.

Thanks!

**Comment by jonboulle** [comment]
There was actually a PR put up recently to add this but it was closed in favour of @purpleidea following up with a reworked version: https://github.com/coreos/go-systemd/pull/210

Feel free to use that one as a starting point, or just creating your own, but probably best to check with @purpleidea

**Comment by purpleidea** [comment]
@jonboulle @cpg1111 I'm actually not personally working on this, I forked @joejulian's version because it was referenced in https://github.com/purpleidea/mgmt/ and changing his PR kept breaking our git master. I'm not sure if he's still working on the upstream patch or not, so I'd ask him, or go for it.

If you'd like to patch mgmt's nspawn resource with your improvements, that would be welcome too!

Cheers

**Comment by joejulian** [comment]
Feel free to take what you want from https://github.com/joejulian/go-systemd/tree/machine1_support and create your own PR. I found some issues with race conditions within systemd and/or systemd-machined that interfere with the work I was doing on mgmt.

Additionally there seemed to be some sort of philosophical problem with the work I was doing and I'm novice enough with golang that I didn't have any idea how to make it acceptable.

**Comment by cpg1111** [comment]
@purpleidea Ah ok.  I have already submitted Pull Request in this repo here https://github.com/coreos/go-systemd/pull/214, it's failing tests due to the need for root to create machines, which I discuss in the PR.  I hadn't come across https://github.com/purpleidea/mgmt/ before, I'll take a look and see if I can submit a Pull Request for that as well.

**Comment by purpleidea** [comment]
On Mon, Nov 21, 2016 at 6:57 PM, Christian Grabowski
<notifications@github.com> wrote:
>
> @purpleidea Ah ok. I have already submitted Pull Request in this repo here #214, it's failing tests due to the need for root to create machines, which I discuss in the PR. I hadn't come across https://github.com/purpleidea/mgmt/ before, I'll take a look and see if I can submit a Pull Request for that as well.

Great! The WIP nspawn code is in resources/nspawn.go Feel free to ping
me on Freenode IRC in #mgmtconfig if you have questions. You'll notice
that there is a temporary fork of this lib under the purpleidea
namespace. Once everything is in git master here, we should kill that
and put it back to normal too.

Cheers!

**Comment by cpg1111** [comment]
https://github.com/coreos/go-systemd/pull/217 adds the additional functionality.  I'm fine closing this issue unless anyone wants this open still?

**Comment by jonboulle** [comment]
lgtm
