### ISSUE TITLE
ListUnitsByNames returns an error

### ISSUE THREAD

**Issue by rebeccaskinner** [coreos/go-systemd#223]
What Happens:

Calling the `ListUnitsByNames` function on `*dbus.Conn` results in an unexpected error:  `Unknown method 'ListUnitsByNames' or interface 'org.freedesktop.systemd1.Manager'`

What I expected to happen:

A slice of `UnitStatus` and no error, or a more descriptive error message.

How to reproduce:

Sample Code:

```
package main
import (
	"fmt"
	"github.com/coreos/go-systemd/dbus"
)

func main() {
	conn, err := dbus.New()
	if err != nil {
		fmt.Println("error getting connection: ", err)
	}
	res, err := conn.ListUnitsByNames([]string{"acpid.service"})
	if err != nil {
		fmt.Println("error with ListUnitsByNames: ", err)
		return
	}
	fmt.Printf("got %d results\n", len(res))
}
```

Test system:

```
uname -a; lsb_release -a
Linux rebecca-vboxdev 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by lucab** [comment]
Which systemd version is this on? `ListUnitsByNames` has been added only recently in https://github.com/systemd/systemd/pull/3182, which should be 232+.

**Comment by dongsupark** [comment]
@lucab I think systemd needs to be v230 or higher for `ListUnitsByNames`, while systemd on Ubuntu xenial is [v229](http://packages.ubuntu.com/xenial/systemd).
So it's recommended to introduce fallback like [this](https://github.com/coreos/fleet/blob/master/systemd/manager.go#L215..L224).

**Comment by rebeccaskinner** [comment]
Okay yeah, I'm on 229.  I've refactored to work around needing the call.  I wonder if it's worthwhile to append a `since: <version>` line to the method comment descriptions?  Happy to take some time to make a PR if that's something that you all think would be valuable.
