### ISSUE TITLE
Systemd-Importd support

### ISSUE THREAD

**Issue by cpg1111** [coreos/go-systemd#232]
Hi there,

Would there be any opposition to implementing support for importd? [importd docs found here](https://www.freedesktop.org/wiki/Software/systemd/importd/).

I'd be happy to implement this and submit a pull request is this is something desired.

Thanks

**Comment by lucab** [comment]
I haven't personally heard of many requests for importd support, but if you have usecases for it we'll gladly review and merge here.

As this systemd-importd is usually not enabled on most distros, please add some runtime detection for tests (so they can be loudly-skipped where support is missing).

**Comment by Xuanwo** [comment]
I'm interested on this too, I will implement it in later few days.
