### ISSUE TITLE
sd_pid_get_owner_uid broken on systemd v234

### ISSUE THREAD

**Issue by iaguis** [coreos/go-systemd#236]
In https://github.com/systemd/systemd/commit/bc9e9af13706dd89dd826c021f6a94f87e637abf, systemd changed errors returned by sd-login functions.

In particular, they're translating `-ENXIO` to `-ENODATA` now to match documentation which [breaks our logic](https://github.com/coreos/go-systemd/blob/24036eb3df68550d24a2736c5d013f4e83366866/util/util_cgo.go#L129).

This breaks rkt: https://github.com/rkt/rkt/issues/3750

**Comment by lucab** [comment]
Thanks for all the references. I think this `-ENODATA` contract goes back to https://github.com/systemd/systemd/commit/707b66c66381c899d7ef640e158ffdd5bcff4deb (v226) but `sd_pid_get_owner_uid()` was left out by mistake, right?

**Comment by iaguis** [comment]
Yep, I think you're right.
