### ISSUE TITLE
dbus: Conn.Reload is broken on systemd-238

### ISSUE THREAD

**Issue by lucab** [coreos/go-systemd#255]
After updating to latest systemd-238, Reload is now broken and the testsuite is failing:
```
--- FAIL: TestReload (0.11s)
        methods_test.go:1524: Message recipient disconnected from message bus without replying
```

**Comment by lucab** [comment]
Chasing libraries and services, the error seems to be originating in the dbus daemon itself: https://cgit.freedesktop.org/dbus/dbus/tree/bus/connection.c?id=395269e0bce3782b0b413fbad89bdb9337b8df9d#n1831

**Comment by lucab** [comment]
This seems to be a regression outside of go-systemd or godbus scope. With plain systemd tools:
```
$ busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager Version
s "238"

$ sudo busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager Reload ; echo $?
Message recipient disconnected from message bus without replying
1
```

This has been observed on latest ContainerLinux nightly:
```
$ uname -r
4.15.7-coreos

$ dbus-daemon --version
D-Bus Message Bus Daemon 1.10.18
```

**Comment by lucab** [comment]
OTOH `systemctl daemon-reload` does not complain. It calls the `Reload` method, and does not get the error from dbus. Instead, it receives the two `Reloading` signals and gently exits after that.

**Comment by lucab** [comment]
Upstream systemd ticket at https://github.com/systemd/systemd/issues/8414

**Comment by muesli** [comment]
Seems fixed upstream and can probably be closed here as well? Fwiw, I can't reproduce it with systemd 238 on Arch.

**Comment by lucab** [comment]
As I mentioned in the upstream ticket, I'm fairly confident this is fixed by the referenced PR in systemd. I'm just waiting confirmation from the original (private) reporter before finally closing this ticket.

**Comment by lucab** [comment]
Confirmed fixing, closed. For anybody hitting this on distros shipping a vanilla systemd-v238, the patch to backport to fix the regression is https://github.com/systemd/systemd/pull/8473/commits/e63ebf71edd7947f29389c72e851d8df5c7bedda
