### ISSUE TITLE
journald: support mocking Send for external consumers

### ISSUE THREAD

**Issue by toravir** [coreos/go-systemd#275]
Is there a way to write go tests to test journal.Send() calls ?? So that i can know for sure all the pieces of data sent are indeed sent to the journald correctly.

**Comment by toravir** [comment]
sdjournal tests writing and reading. But in my package i am just using journald to write. I cannot use sdjournal to read back - since sdjournal requires the underlying system to have libsystemd-dev. Is there some mock mechanism to check if the data is sent correctly over the unix Socket ??

**Comment by lucab** [comment]
At the moment a consumer cannot mock or hijack the socket for `journal.Send`. While I am not sure this is something we actually want to expose, I think it may be feasible after the rework described in https://github.com/coreos/go-systemd/pull/218#issuecomment-274490875 is done.

Why do you want to externally test `journal.Send` behavior? This should pertain to library tests, without exposing all internals knobs to consumers.
Can you just hijack `/run/systemd/journal/socket` in your environment?

**Comment by toravir** [comment]
A library that uses journal.Send(), needs to write a test - like in https://github.com/rs/zerolog/blob/master/journald/journald_test.go, it can verify the data being given to the library is sent correctly to the systemd.

I want to write go-tests - so i am looking for some mock that is process specific (so that the test can run in an env with and without systemd). It is just like mock "net/http/httptest" package. I can code up and send a PR if you are willing to consider a mock ??

**Comment by lucab** [comment]
If you want to check that the data has been properly recorded in journald then the way to go is indeed the `sdjournal` package, which requires a running systemd-journald + libsystemd. If you aren't in such environment and don't actually care about journald behavior, then just place your own receiver behind a unix socket at `/run/systemd/journal/socket`.

In general no, I'm not eager to expose testing/mocking interface through this library. The further we can go in here is making the socket endpoint configurable, but even that currently requires ground rework (see link above).

**Comment by lucab** [comment]
@toravir FYI https://github.com/coreos/go-systemd/pull/279/files#diff-985ded8023b21268d0d5cf7f29781d2eR55.
