### ISSUE TITLE
dbus: ListUnits does not behave as documented

### ISSUE THREAD

**Issue by lucab** [coreos/go-systemd#289]
[Conn.ListUnits](https://godoc.org/github.com/coreos/go-systemd/dbus#Conn.ListUnits) currently says:
>  ListUnits returns an array with all currently loaded units.

However there are been reports from the field that its behavior is somewhat puzzling and some loaded units are missing from the returned array. In particular, @SuperQ noticed that Prometheus node_exporter is encountering https://github.com/prometheus/node_exporter/issues/1082 in a consistent way across multiple OSes and systemd versions.

This code and documentation has been there for a long time, so it could be either a case of wrong documentation or behavioral change that slipped in. It would be good to read through systemd server-side implementation and then update go-systemd logic and/or documentation.

**Comment by miono** [comment]
According to @poettering in this systemd-issue: https://github.com/systemd/systemd/issues/5063 systemd isn't supposed to report units that aren't loaded when using the ListUnits-method of the Manager-interface.

Units that are neither enabled or started aren't actually loaded. (`systemctl status` actually loads the unit for the purpose of displaying information but unloads it immediately after the status has been displayed).

The issue i linked from systemd is about the unclear documentation of respect to this.

So I suggest changing the documentation to be more clear about what to expect when calling `func (c *Conn) ListUnits()`

**Comment by SuperQ** [comment]
Seems reasonable. Is there a method to get a list of disabled units?

**Comment by miono** [comment]
Not that I've found. But there is ListUnitFiles, which is already implemented in go-systemd.

**Comment by miono** [comment]
@lucab My first time contributing to go-systemd (or anything else for that matter), please let me know if I did something wrong.

**Comment by lucab** [comment]
Looking at systemd, `systemctl list-unit --all` [simply does](https://github.com/systemd/systemd/blob/v239/src/systemctl/systemctl.c#L597) a `ListUnitsByPatterns` with empty arguments (and [falls back](https://github.com/systemd/systemd/blob/v239/src/systemctl/systemctl.c#L624) to `ListUnitsFiltered`). This also returns loaded but inactive units.

For other cases, e.g. disabled or masked unit files, the equivalent `ListUnitFiles*` will act on **unit files** instead.

**Comment by miono** [comment]
> This also returns loaded but inactive units.

This exactly pinpoints what's confusing about it all: Knowing the logic for when a unit is loaded. You can do `systemctl status <unloaded unit>`, which will make systemd load the unit ad hoc for the purpose of displaying information about it. So it looks loaded in the terminal output, but is immediately un-loaded again by systemd.

_loaded but inactive units_ only matches "started" units.
