### ISSUE TITLE
Journal entry not written when process ends too quickly

### ISSUE THREAD

**Issue by Richterrettich** [coreos/go-systemd#314]
In case the main process ends too quickly, no log entries are written to the journal. I have tested fd7a80b32e1fc73e890fde45604ed5009dc817a3 as well as https://github.com/coreos/go-systemd/tree/v17

## Minimal working example

```go
package main

import (
	"github.com/coreos/go-systemd/journal"
)

func main() {
	err := journal.Send("hello", journal.PriInfo, nil)
	if err != nil {
		panic(err)
	}
}
```
`go build && ./journald-test && sudo journalctl $PWD/journald-test `

finds no log entries.

```go
package main

import (
	"time"

	"github.com/coreos/go-systemd/journal"
)

func main() {
	err := journal.Send("hallo", journal.PriInfo, nil)
	if err != nil {
		panic(err)
	}
	time.Sleep(1 * time.Second)
}
```

`go build && ./journald-test && sudo journalctl $PWD/journald-test `

finds the following log entry:

`Jul 29 11:01:32 localhost.localdomain journald-test[30841]: hallo`

## Tested Environments

- Centos 7.6
```bash
systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```
- Fedora 30 
```bash
systemctl --version
systemd 241 (v241-9.gitb67ecf2.fc30)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Comment by lucab** [comment]
I have some suspicion that the log entries may be in the journal, just not attached to any specific unit/slice (as the process exit destroys some info, and journald is racing to gather them).
Can you try passing `-o json -a` to `journalctl` and manually digging to see if they are there?

**Comment by Richterrettich** [comment]
Thank you for the hint! You are correct, the log entry is indeed present (I altered the message to distinguish the log entries):
`sudo journalctl -o json -a _COMM=journald-test | jq`
```json
{
  "_SYSTEMD_INVOCATION_ID": "0fc07a52f947427596da84fb4380ec98",
  "_BOOT_ID": "6e531ef7e2fb42ce86d791ff88d8b1a8",
  "_SOURCE_REALTIME_TIMESTAMP": "1564395037362241",
  "_TRANSPORT": "journal",
  "_SELINUX_CONTEXT": "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023",
  "_SYSTEMD_SLICE": "user-1000.slice",
  "_SYSTEMD_SESSION": "2",
  "_CAP_EFFECTIVE": "0",
  "_UID": "1000",
  "__REALTIME_TIMESTAMP": "1564395037362459",
  "_SYSTEMD_USER_SLICE": "-.slice",
  "__CURSOR": "s=0a0629654b2341a68ffe2b3530635da8;i=9b919;b=6e531ef7e2fb42ce86d791ff88d8b1a8;m=17926e9f8;t=58ecf1a7d891b;x=b33d2fd314aee52c",
  "_GID": "976",
  "_SYSTEMD_CGROUP": "/user.slice/user-1000.slice/session-2.scope",
  "_AUDIT_LOGINUID": "1000",
  "_COMM": "journald-test",
  "_PID": "24031",
  "_SYSTEMD_OWNER_UID": "1000",
  "MESSAGE": "hallo welt",
  "_SYSTEMD_UNIT": "session-2.scope",
  "PRIORITY": "6",
  "_AUDIT_SESSION": "2",
  "__MONOTONIC_TIMESTAMP": "6327560696",
  "_HOSTNAME": "localhost.localdomain",
  "_MACHINE_ID": "46cb97fc41ab4a6daec84fc2b850730e"
}
```
I tried it a couple of times and the results are consistent. The easiest workaround is something like this: `sudo journalctl  _COMM=journald-test` instead of this `sudo journalctl  /usr/bin/journald-test`.

For my use case, this is fine. I leave it up to you what we should do with this issue. I have no idea if it is possible or economical to fix this issue in this project. If you think this has no wider implications we could just document the behaviour.

**Comment by lucab** [comment]
> For my use case, this is fine. I leave it up to you what we should do with this issue. I have no idea if it is possible or economical to fix this issue in this project. If you think this has no wider implications we could just document the behaviour.

This is already tracked upstream as https://github.com/systemd/systemd/issues/2913. It is way deeper than anything go-systemd could do, and it's a limitation of the kernel to userspace interface. I'm just closing this ticket here, interested parties should directly watch the systemd one instead.
