### ISSUE TITLE
go-systemd is not a valid go module

### ISSUE THREAD

**Issue by moshloop** [coreos/go-systemd#320]
Running `go get github.com/coreos/go-systemd` fails with:

`unexpected status (https://goproxy.io/github.com/coreos/go-systemd/@v/list): 404 Not Found`

This is due to semver not being applied correctly i.e. the repository should have a tag `v21.0.0`, not just `v21`

**Comment by lucab** [comment]
Thanks for the report.
This should have been a transient error, as we were in the process of switching to Go modules between `v21` and `v22.0.0`. You can read the whole plan and story at https://github.com/coreos/go-systemd/pull/307. It should be fine now as we completed the switch.

For reference, there are two relevant releases for library consumers:
 * https://github.com/coreos/go-systemd/releases/tag/v21 - last one without Go modules versioning and imports, it comes with a `dep` manifest
 * https://github.com/coreos/go-systemd/releases/tag/v22.0.0 - first one with support for Go modules layout
