### ISSUE TITLE
build command-line-arguments: cannot load github.com/coreos/go-systemd/journal: module github.com/coreos/go-systemd/journal: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by chr1043086360** [coreos/go-systemd#322]
```
package etcd

import (
	"fmt"
	"time"

	"github.com/coreos/etcd/clientv3"
)

func Etcd() {
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"localhost:2379"},
		DialTimeout: 5 * time.Second,
	})
	if err != nil {
		fmt.Println("connect failed, err:", err)
		return
	}
	fmt.Println("connect success")
	defer cli.Close()
}
```

**Comment by lucab** [comment]
@chr1043086360 please double-check your network/proxy/etc, I think you ended up with an HTML page instead of a Go source file.

**Comment by lucab** [comment]
@chr1043086360 any update on this?

I'm proceeding to close this as it seems to be 1) a local (possibly network) issue 2) coming through `etcd/clientv3`.

If you are still having issues, feel free to follow up. It could be more helpful to forward and debug your issues on the `etcd` bug-tracker.
