### ISSUE TITLE
when i install go-micro, i found that your package can not install lastest version with proxy url

### ISSUE THREAD

**Issue by zhaojingtao** [coreos/go-systemd#324]
when i install go-micro, i found that your package can not install lastest version in proxy url (i had tried many proxy,such as alibaba,gonexus.dev and so on),they all both had same result, not found or 400 

https://goproxy.io/github.com/coreos/go-systemd/@v/list
the page will report:" not found "

but in other golang package ,you can find that its list will show you some information
such as : https://goproxy.io/github.com/pkg/errors/@v/list

can author edit this version list file in your package to solve this problem

**Comment by lostz** [comment]
me too

**Comment by lucab** [comment]
Thanks for the report.
Unfortunately I don't have direct insights/control into proxy services, so it may be more useful to just report this to the service developers/owners to investigate what's going on.

Looking a bit around over there, I see that `v22.0.0` seems to be present there: https://goproxy.io/github.com/coreos/go-systemd/v22/@v/.

**Comment by zhaojingtao** [comment]
when i use golang 1.13, i can download the whole go-micro resp.
so i think this issue is not a problem .thanks, lucab
