### ISSUE TITLE
cannot find module providing package github.com/coreos/go-systemd/journal 

### ISSUE THREAD

**Issue by Dragonbuf** [coreos/go-systemd#328]
when `go get github.com/coreos/go-systemd` will report `cannot find module providing package github.com/coreos/go-systemd/journal `

**Comment by lucab** [comment]
Current version of go-systemd uses Go modules, and thus follow its import rules. See https://github.com/coreos/go-systemd/issues/321 for a detailed discussion about the differences.

Duplicate of #321. Closing.
