### ISSUE TITLE
Solving failure: "github.com/coreos/go-systemd/util" imports "github.com/coreos/go-systemd/v22/internal/dlopen", which contains malformed code: no package exists at "github.com/coreos/go-systemd/v22/internal/dlopen"

### ISSUE THREAD

**Issue by ThinkingXuan** [coreos/go-systemd#338]

**Comment by lucab** [comment]
This is likely due to your source project using Go module and a wrong import path.
The correct import path for the `util` module would be `github.com/coreos/go-systemd/v22/util`.

**Comment by lucab** [comment]
Closing as a duplicate of https://github.com/coreos/go-systemd/issues/321.
