### ISSUE TITLE
dlopen_test.go:54:15: undefined: strlen

### ISSUE THREAD

**Issue by eclipseo** [coreos/go-systemd#339]
Go 1.15 beta 1 on Fedora Rawhide, during go testing:

```
github.com/coreos/go-systemd/internal/dlopen
# github.com/coreos/go-systemd/internal/dlopen [github.com/coreos/go-systemd/internal/dlopen.test]
./dlopen_test.go:54:15: undefined: strlen
FAIL    github.com/coreos/go-systemd/internal/dlopen [build failed]
```

**Comment by lucab** [comment]
This seems to be working fine both in my local environment (go1.15.5) and in CI: https://github.com/coreos/go-systemd/runs/1412766487?check_suite_focus=true.

**Comment by lucab** [comment]
It works in CI, closing ticket due to lack of further inputs.

**Comment by lucab** [comment]
On a second check, the test job was missing a key part of its logic and the CI was not properly set up to run it.
https://github.com/coreos/go-systemd/pull/412 is up to fix this.
