### ISSUE TITLE
concurrency safety?

### ISSUE THREAD

**Issue by phemmer** [coreos/go-systemd#381]
I cant find any comment in the documents that state whether the various packages are concurrent safe.

For example, if I'm using the `dbus` package, and I fire off 2 simultaneous calls, will they step on each other? Do I need to ensure separate connections are used for each?

**Comment by lucab** [comment]
Hi and welcome! It should be generally ok to use a single connection for multiple concurrent operations. That said, there may be bugs breaking some usecases; did you encounter any specific troubles?

**Comment by phemmer** [comment]
no, just impacts application design whether I need to be opening multiple connections, or whether I can share one.

**Comment by phemmer** [comment]
Closing. Have decided not to use go-systemd as it would require too many changes to work well.
