### ISSUE TITLE
No way to wait for dbus.ReloadContext completion

### ISSUE THREAD

**Issue by phemmer** [coreos/go-systemd#383]
Currently `dbus.ReloadContext()` doesn't provide any way to wait for reload to complete. This is causing race conditions in my code as I need to wait for completion.

I think the best way to address the problem would be to have `ReloadContext()` accept a chan argument like other functions do (e.g. `StartUnitContext`) that can be used to block on. Though this would result in a breaking API change.

**Comment by phemmer** [comment]
Closing. Have decided not to use go-systemd as it would require too many changes to work well.

**Comment by lucab** [comment]
I'm not sure what you are seeing, but `dbus.ReloadContext()` itself should call to the manager `Reload()` method and return after that one does.
Other than that, any kind of asynchronicity you are seeing is likely coming from systemd manager itself.

**Comment by phemmer** [comment]
https://github.com/coreos/go-systemd/blob/f9f254610339c14ad7c50e9352848c7ff62fc81f/dbus/methods.go#L775-L777

^ It fires off a job and does not wait for completion.

**Comment by lucab** [comment]
The `Call()`/`CallWithContext()` are blocking remote calls, see https://pkg.go.dev/github.com/godbus/dbus/v5#Object.Call.
The `.Store()` bit in there is responsible for spewing back the result/error from the remote, after the `Call` completed synchronously.

Except if there are bugs lying somewhere in godbus, the code you quoted should return with success if and only after the remote DBus call completed with success on the systemd manager side.
