### ISSUE TITLE
Writing `UNIT` to journal

### ISSUE THREAD

**Issue by ginglis13** [coreos/go-systemd#403]
I'm attempting to write a message to the journal using [`journal.Send()`](https://github.com/coreos/go-systemd/blob/f5f8d59a116b1ca501dd87cdb28f6ce89ccf58dc/journal/journal_unix.go#L79). I'd like to write this message for a specific service, so I've added vars as

```
vars := map[string]string{
   "UNIT": "myservice.service",
}
err = journal.Send(message, journal.PriInfo, vars)
```

I am seeing the log appear in the journal via `journalctl -f`, but it's appearing as `main[12345] <message>` when I was expecting the log entry to appear as `myservice[12345] <message>`. Likewise, I do not see the log via `journalctl -f -u myservice`. Am I missing something here or is the `UNIT` field (https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html) unsupported by this library? Thanks

**Comment by lucab** [comment]
I think this really depends on how you are running your example, so I can't exactly say.
I suggest running something like `sudo journalctl -o json` and then inspect the actual metadata of your message this way.
This is unlikely to be a library bug, so unless you find further evidence in that direction I'm inclined to close this for now.
