### ISSUE TITLE
Any method for read journal 

### ISSUE THREAD

**Issue by dlintw** [coreos/go-systemd#70]
It will be better if provide API for read journal like python
http://www.freedesktop.org/software/systemd/python-systemd/journal.html#accessing-the-journal

**Comment by ChimeraCoder** [comment]
For what it's worth, I've been working on a client for this here: https://github.com/ChimeraCoder/journalctl-go

It's still a work in progress or I'd submit a pull request here, but I figured I'd post it in case you or others still need this in the meantime.

**Comment by sathieu** [comment]
Hasn't it be done with https://github.com/coreos/go-systemd/commit/0020698a980adf8a2c440d9be709edc85b54544a?

**Comment by jonboulle** [comment]
yes, thanks for catching!
