### ISSUE TITLE
journal.init not exported

### ISSUE THREAD

**Issue by mwhooker** [coreos/go-systemd#73]
forgive me if there's an obvious solution, but the journal code looks unusable since one can't initialize the socket connection from outside the library.

**Comment by mwhooker** [comment]
oops, sorry, it's late

**Comment by bcwaldon** [comment]
@mwhooker can you shed any more light on this? Just in case someone else finds this issue in the future...

**Comment by mwhooker** [comment]
of course, I forgot that the `init()` function is run automatically when the module is imported
