### ISSUE TITLE
Add Conn.ListUnitFiles.

### ISSUE THREAD

**Issue by ericsnowcurrently** [coreos/go-systemd#76]
Unfortunately the `ListUnits` method does not fill my needs.  An enabled (but inactive) unit may not show up under some conditions.  I've run into this consistently.

The implementation should be virtually identical to `ListUnits`.  `ListUnitFiles` is a dbus method on the manager object (per the docs).

**Comment by geeks-dev** [comment]
+1

**Comment by jonboulle** [comment]
fixed via #135
