### ISSUE TITLE
v3 tag for package?

### ISSUE THREAD

**Issue by booleancandy** [coreos/go-systemd#90]
Hi everyone.  I was wondering if a tag could be made for a release of go-systemd?  I've been working on updating the Debian packaging for go-systemd and would like to package a release instead of merely a snapshot.  

I was going to go out on a limb and say that since there haven't been many commits recently maybe a release tag is in order but there have been a few fixes and merges since I last updated my local copy.  Obviously it's up to you guys.

Thanks,

Tim.

**Comment by LK4D4** [comment]
Yup, I want tag too :)

**Comment by tianon** [comment]
+1

Any particular blockers for a new tag? :smile:

**Comment by philips** [comment]
@tianon @LK4D4 tagged https://github.com/coreos/go-systemd/releases/tag/v3

**Comment by tianon** [comment]
Super belated thanks, @philips :heart:
