### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by robertlabrie** [coreos/go-systemd#97]
I'm filing this because I want SkyDNS on windows, but I won't resent a "wont fix" close. Obviously there is no hope of systemd on windows....

C:\Users\rober_000\Documents>go build github.com/skynetservices/skydns
github.com/coreos/go-systemd/activation
C:\Projects\Go\src\github.com\coreos\go-systemd\activation\files.go:47: cannot use fd (type int) as type syscall.Handle in argument to syscall.CloseOnExec

**Comment by jonboulle** [comment]
@robertlabrie why does SkyDNS depend on go-systemd? seems like this would be better filed there, so they can remove that dependency on non-Linux builds..

**Comment by robertlabrie** [comment]
They told me to cross post here, and in the end, said he'd accept a PR
which excluded systemd on Windows builds. Doing that is burred in my
backlog. Thanks for the response.

**Comment by jonboulle** [comment]
no worries, sorry about the delay!
