### ISSUE TITLE
go-systemd is broken at head

### ISSUE THREAD

**Issue by jcgregorio** [coreos/go-systemd#98]
Looks like an upstream dependency changed:

$ go get github.com/coreos/go-systemd/dbus
# github.com/coreos/go-systemd/dbus
src/github.com/coreos/go-systemd/dbus/dbus.go:186: cannot use conn.Object("org.freedesktop.systemd1", dbus.ObjectPath("/org/freedesktop/systemd1")) (type dbus.BusObject) as type *dbus.Object in return argument: need type assertion

**Comment by hinnerk** [comment]
This patch works for me on OS X 10.10.4, Go version 1.4.2.

**Comment by pquerna** [comment]
fixed by #100
